# Generated by Django 2.1.4 on 2019-01-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaple_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaple_core.Event'),
        ),
    ]
