# Generated by Django 2.1.5 on 2019-01-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaple_core', '0002_auto_20190104_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sound_type',
            field=models.CharField(choices=[('NONE', 'Keine'), ('SPCH', 'Sprache'), ('CNCT', 'Konzert'), ('MNTR', 'Konzert mit Monitor')], default='', max_length=8),
        ),
    ]
