# Generated by Django 2.1.5 on 2019-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaple_core', '0004_auto_20190114_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path='/home/reinhardt/projects/vaple/files', recursive=True, verbose_name='Ordner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ba',
            field=models.FilePathField(blank=True, null=True, path='/home/reinhardt/projects/vaple/files', recursive=True, verbose_name='BA'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rider',
            field=models.FilePathField(blank=True, null=True, path='/home/reinhardt/projects/vaple/files', recursive=True),
        ),
    ]
