# Generated by Django 2.1.5 on 2019-01-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaple_core', '0007_auto_20190114_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Raum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sound_type',
            field=models.CharField(choices=[('NONE', 'Keine'), ('SPCH', 'Sprache'), ('CNCT', 'Konzert'), ('MNTR', 'Konzert mit Monitor')], default=('NONE', 'Keine'), max_length=8, verbose_name='Beschallungsart'),
        ),
    ]
