# Generated by Django 2.1.5 on 2019-01-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaple_core', '0008_auto_20190114_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='sound_type',
            field=models.CharField(choices=[('NONE', 'Keine'), ('SPCH', 'Sprache'), ('CNCT', 'Konzert'), ('MNTR', 'Konzert mit Monitor')], default='NONE', max_length=8, verbose_name='Beschallungsart'),
        ),
        migrations.AddField(
            model_name='event',
            name='employees',
            field=models.ManyToManyField(to='vaple_core.Employee'),
        ),
    ]
