# Generated by Django 2.1.5 on 2019-01-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaple_core', '0011_auto_20190116_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='employees',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='Veranstaltungstermin', to='vaple_core.Employee', verbose_name='Mitarbeiter'),
        ),
    ]
